import { Hero } from "../models/hero.module";

export const HEROES: Hero[] = [
    { id: 1, name: 'Fade', imgURL: 'https://cdn.oneesports.gg/cdn-data/2022/04/VALORANT_Fade_Banner_Art-1536x864.jpg', description: 'Turkish bounty hunter Fade unleashes the power of raw nightmare to seize enemy secrets. Attuned with terror itself, she hunts down targets and reveals their deepest fears - before crushing them in the dark.' },
    { id: 2, name: 'Jackie Chan', imgURL: 'https://icon2.cleanpng.com/20180201/dcq/kisspng-display-resolution-wallpaper-jackie-chan-png-clipart-5a738bcf1aa8a0.1169273915175218711092.jpg', description: 'Jackie Chan is a professional archaeologist with a high degree of martial combat skill' },
    { id: 3, name: 'Blade', imgURL: 'https://kanto.legiaodosherois.com.br/w760-h398-gnw-cfill-q95/wp-content/uploads/2021/07/legiao_q7uky31w_Tap.png.jpeg', description: 'Blade is known as The Vampire Hunter, as he uses his anti-vampiric gifts to fight supernatural creatures.' },
    { id: 4, name: 'Gojo', imgURL: 'https://i1.sndcdn.com/artworks-KQCuYKIGRerZWn88-esGz5g-t500x500.jpg', description: 'Satoru Gojo is known in Jujutsu society as the strongest Jujutsu Sorcerer. He earned this nickname due to the superhuman amounts of Cursed Energy he possesses. Gojos Cursed Energy is vast enough to use a Mastery Expansion multiple times a day, while most Sorcerers can only use it once.' },
    { id: 5, name: 'Goku', imgURL: 'https://i.pinimg.com/564x/05/c9/ef/05c9efba9a18c62ab8a38fce446a0063.jpg', description: 'Goku is the character who has the most knowledge of battle techniques. Saiyans are a warrior race, and one of their special abilities is that they become stronger after being seriously injured, and if they get to the point of almost dying from severe physical injuries and recover, their fighting power will increase incredibly what it is called zenkai.' },
    { id: 6, name: 'Hulk', imgURL: 'https://i.pinimg.com/564x/78/76/49/787649eac99ed3897155f5d0e594df2e.jpg', description: 'The Hulk is typically seen as a hulking man with green skin, hair, and eyes, wearing only a pair of torn purple pants that survive his physical transformation as the character progressed.' },
    { id: 7, name: 'Kratos', imgURL: 'https://i.pinimg.com/564x/4e/cd/b4/4ecdb4fb06f743ff5fe4bda649549234.jpg', description: 'Kratos was the son of Zeus and a mortal named Callisto. Kratos was a Spartan kid who helped train his brother, Deimos, and Deimos was taken by Ares and Athena. Kratos was once a general in the Spartan armies, and he was well known for his ruthlessness.' },
    { id: 8, name: 'Van Helsing', imgURL: 'https://i.pinimg.com/564x/8a/d5/e9/8ad5e93647d76665ef721b4ae6c29298.jpg', description: 'a man of medium height, strongly built, with his shoulders set back over a broad, deep chest and a neck well balanced on the trunk as the head is on the neck.' },
    { id: 9, name: 'Sasori', imgURL: 'https://i.pinimg.com/564x/4d/ce/40/4dce408f3be4c4e2503f38f9b27b0bcc.jpg', description: 'Sasori was a very powerful shinobi, being able to, with effort, defeat and kill the Third Kazekage, the strongest ninja in Sunas history. His use of his puppets was greatly feared throughout the Third Shinobi World War as he turned the sand red with blood, giving him the nickname, "Sasori of the Red Sand".' },
    { id: 10, name: 'Max Payne', imgURL: 'https://i.pinimg.com/564x/15/21/c2/1521c20a654da424bc42f4f61345807a.jpg', description: 'Max Payne is a man with nothing to lose in the violent, cold urban night. A fugitive undercover cop framed for murder and now hunted by cops and the mob. Max is a man with his back against the wall, fighting a battle he cannot hope to win.' }
];
